FROM amazoncorretto:11-alpine-jdk
MAINTAINER juanjgfredes
COPY . .
RUN apk update && apk upgrade
RUN apk add maven
RUN mvn clean package
EXPOSE 8080
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
