version: "3.8"
services:
  db:
    container_name: escuela-db
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: escuela
    volumes:
      - "escuela-mysql-data:/var/lib/mysql"
  app:
    container_name: escuela-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/escuela?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    depends_on:
      - db
volumes:
  escuela-mysql-data:

