version: "3.8"
services:
  db:
    container_name: escuela-db
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: escuela
    volumes:
      - "escuela-mysql-data:/var/lib/mysql"
  app:
    container_name: escuela-app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/escuela?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    depends_on:
      - db
    command: sh -c "mvn liquibase:update -Dliquibase.url=jdbc:mysql://db/escuela -Pdev && java -jar /opt/app/target/escuela-0.0.1-SNAPSHOT.jar"
volumes:
  escuela-mysql-data:

