FROM amazoncorretto:11-alpine-jdk
MAINTAINER juanjgfredes
COPY . .
RUN apk update && apk upgrade
RUN apk add maven
RUN mvn clean package
RUN mvn liquibase:update -Pprod
ENV VARIABLE_NOMBRE=VALOR
ENV OTRA_VARIABLE=OTRO_VALOR
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "/target/escuela-0.0.1-SNAPSHOT.jar"]
